services:
  app:
    image: amazoncorretto:21
    container_name: app
    env_file: .env # 環境変数の定義に.envを利用
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./server:/srv:cached
    working_dir: /srv
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:5.7
    container_name: db
    env_file: .env # 環境変数の定義に.envを利用
    ports:
      - "3306:3306" #ポート番号の設定
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "$MYSQL_USER", "-p$MYSQL_PASSWORD"]
        interval: 30s
        timeout: 5s
        retries: 6
        start_period: 30s
    volumes:
      - ./docker/db/initdb:/docker-entrypoint-initdb.d
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
