insert into posts (user_id, content, created_at, created_user, updated_at, updated_user) values
 (1, 'test', CURRENT_TIMESTAMP, '竹内大貴', CURRENT_TIMESTAMP, '竹内大貴'),
 (1, 'test', CURRENT_TIMESTAMP, '竹内大貴', CURRENT_TIMESTAMP, '竹内大貴'),
 (1, 'test', CURRENT_TIMESTAMP, '竹内大貴', CURRENT_TIMESTAMP, '竹内大貴'),
 (1, 'test2', CURRENT_TIMESTAMP, '竹内大貴', CURRENT_TIMESTAMP, '竹内大貴'),
 (1, 'test2', CURRENT_TIMESTAMP, '竹内大貴', CURRENT_TIMESTAMP, '竹内大貴'),
 (1, 'aaaa', CURRENT_TIMESTAMP, '竹内大貴', CURRENT_TIMESTAMP, '竹内大貴'),
 (1, 'aaa', CURRENT_TIMESTAMP, '竹内大貴', CURRENT_TIMESTAMP, '竹内大貴'),
 (1, 'aaaa', CURRENT_TIMESTAMP, '竹内大貴', CURRENT_TIMESTAMP, '竹内大貴'),
 (1, 'aaaa', CURRENT_TIMESTAMP, '竹内大貴', CURRENT_TIMESTAMP, '竹内大貴'),
 (1, 'test', CURRENT_TIMESTAMP, '竹内大貴', CURRENT_TIMESTAMP, '竹内大貴'),
 (1, 'aaa', CURRENT_TIMESTAMP, '竹内大貴', CURRENT_TIMESTAMP, '竹内大貴'),
 (1, 'ああああ', CURRENT_TIMESTAMP, '竹内大貴', CURRENT_TIMESTAMP, '竹内大貴'),
 (1, 'っっっb', CURRENT_TIMESTAMP, '竹内大貴', CURRENT_TIMESTAMP, '竹内大貴'),
 (2, 'tst', CURRENT_TIMESTAMP, 'テスト', CURRENT_TIMESTAMP, 'テスト'),
 (1, 'じゅげむ　じゅげむ　ごこうのすりきれ　かいじゃりすいぎょの　すいぎょうまつ　うんらいまつ　ふうらいまつ', CURRENT_TIMESTAMP, '竹内大貴', CURRENT_TIMESTAMP, '竹内大貴'),
 (2, 'すいぎょうまつ　うんらいまつ　ふうらいまつ　くうねるところにすむところ　やぶらこうじのぶらこうじ', CURRENT_TIMESTAMP, 'テスト', CURRENT_TIMESTAMP, 'テスト'),
 (1, 'くぇrちゅいおp＠あsdfghjkl；：zxcvbんm、。・＿１２３４５６７８９０ー＾￥くぇrちゅいおp＠「あsdfghjkl；：', CURRENT_TIMESTAMP, '竹内大貴', CURRENT_TIMESTAMP, '竹内大貴'),
 (1, '１２３４５６７８９０ー＾￥くぇrちゅいおp＠「あsdfghjkl；：」zxcvbんm、。・＿１２３４５６７８９０ー＾￥くぇrちゅいおp＠「あsdfghjkl；：」zxcvbんm、。・＿１２３４５６７８９０ー', CURRENT_TIMESTAMP, '竹内大貴', CURRENT_TIMESTAMP, '竹内大貴'),
 (3, 'aaa', CURRENT_TIMESTAMP, 'test2', CURRENT_TIMESTAMP, 'test2'),
 (4, 'aaabbbccc', CURRENT_TIMESTAMP, 'testeste', CURRENT_TIMESTAMP, 'testeste'),
 (1, 'じゅげむ　じゅげむ　ごこうのすりきれ　かいじゃりすいぎょの　すいぎょうまつ　うんらいまつ　ふうらいまつ　くうねるところにすむところ　やぶら', CURRENT_TIMESTAMP, '竹内大貴', CURRENT_TIMESTAMP, '竹内大貴'),
 (2, '１２３４５６７８９０ー＾￥くぇrちゅいおp＠「あsdfghjkl；：」zxcvbんm、。・＿１２３４５６７８９０ー＾￥くぇrちゅいおp＠「あsdfghjkl；：」zxcvbんm、。・＿１２３４５６７８９０ー	', CURRENT_TIMESTAMP, 'テスト', CURRENT_TIMESTAMP, 'テスト'),
 (2, '今どうしてる？', CURRENT_TIMESTAMP, 'テスト', CURRENT_TIMESTAMP, 'テスト'),
 (2, 'ああああ', CURRENT_TIMESTAMP, 'テスト', CURRENT_TIMESTAMP, 'テスト');
